title: LocalMind Documentation
description: Local AI prompt runner documentation
baseurl: "/localmind"  # your repo name
url: "https://jeffsebring.github.io"
theme: jekyll-theme-slate
# or for no theme at all
# theme: null

